In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6,7])
print(arr1,type(arr1))
arr2= np.array([1,2,3,4,'prime'])
print(arr2,arr2.dtype)
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3,arr3.shape)

[1 2 3 4 5 6 7] <class 'numpy.ndarray'>
['1' '2' '3' '4' 'prime'] <U21
[[1 2 3]
 [4 5 6]] (2, 3)


In [3]:
arr1=np.ones((2,3))
print(arr1,arr1.shape)

arr2=np.zeros((4,3))
print(arr2,arr2.shape)

arr3=np.full((2,3),5)
print(arr3,arr3.shape)

arr4= np.eye(3)
print(arr4,arr4.shape)

arr5=np.arange(1,20,2)
print(arr5)

arr6=np.linspace(1,10,5)
print(arr6)

[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (4, 3)
[[5 5 5]
 [5 5 5]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  3  5  7  9 11 13 15 17 19]
[ 1.    3.25  5.5   7.75 10.  ]


In [4]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print(arr1.dtype)

arr=np.array([1,2,3,4],dtype='U')
print(arr,arr.dtype)
arr=arr.astype('float64')
print(arr,arr.dtype)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
12
3
int64
['1' '2' '3' '4'] <U1
[1. 2. 3. 4.] float64


In [5]:
arr=np.array([1,2,3,4,5,6])
arr=arr.reshape((2,3))
print(arr,arr.shape)
arr=arr.flatten()
print(arr,arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[1 2 3 4 5 6] (6,)


In [6]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0][1])
print(arr[2][2])
arr=arr.flatten()
idx=[1,3,4]
print(arr[idx])
print(arr[arr>2])
print(arr[arr%2==0])

2
9
[2 4 5]
[3 4 5 6 7 8 9]
[2 4 6 8]


In [7]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[2:])
print(arr[:3])
print(arr[:])
print(arr[2:4])
print(arr[1:4:2])

[3 4 5 6 7]
[1 2 3]
[1 2 3 4 5 6 7]
[3 4]
[2 4]


In [9]:
arr=np.array([1,2,3,4,5,6,7])
arr1=arr[2:5] # arr1 did not store any copy it stored a view thats why when we made changes on any index that changes to the original 
arr1[0]=88
print(arr1)
print(arr)
#so we need a copy
arr=np.array([1,2,3,4,5,6,7])
arr1=arr[2:5].copy() 
arr1[0]=88
print(arr1)
print(arr)

py_arr=[1,2,3,4,5,6,7]
py_arr1=py_arr[2:5]  
py_arr1[0]=88
print(py_arr1)
print(py_arr)

[88  4  5]
[ 1  2 88  4  5  6  7]
[88  4  5]
[1 2 3 4 5 6 7]
[88, 4, 5]
[1, 2, 3, 4, 5, 6, 7]


In [12]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
col_sum=np.sum(arr2D,axis=0)
row_sum=np.sum(arr2D,axis=1)
print(col_sum)
print(row_sum)

sliced=arr2D[0:3,1:3]
print(sliced)


[22 26 30]
[ 6 15 24 33]
[[2 3]
 [5 6]
 [8 9]]


In [19]:
arr3D=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3D[0][1][0]) 
print(arr3D[0,1,0]) 
print(arr3D[1][0][1])
print(arr3D[:,:,0])
print(arr3D[0,1,:])
arr3D[0,1,1]=88
arr3D[1][1][1]=88
# Comma syntax (arr[a,b,c]) → NumPy indexing
# Colon (:) anywhere → slicing
print(arr3D)

3
3
6
[[1 3]
 [5 7]]
[3 4]
[[[ 1  2]
  [ 3 88]]

 [[ 5  6]
  [ 7 88]]]
